name: heroes_app
description: Encuentra promociones cercas de ti.

publish_to: "none"

version: 1.0.0+12

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Icons
  cupertino_icons: ^1.0.2
  ionicons: ^0.2.2

  #Network
  dio: ^5.3.2

  flutter_bloc: ^8.1.2

  get_it: ^7.6.0
  auto_route: ^7.8.3
  shared_preferences: ^2.2.1
  flutter_native_splash: ^2.3.1
  flutter_form_builder: ^9.1.1
  flutter_map: ^6.1.0
  equatable: ^2.0.0
  provider: ^6.0.5
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.14.0
  bloc: ^8.1.2
  adaptive_theme: ^3.4.1
  image_picker: ^1.0.4
  firebase_storage: ^11.4.0
  intl: ^0.18.0
  form_builder_extra_fields: ^10.1.0
  flutter_slidable: ^3.0.1
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  url_launcher: ^6.2.2
  geocoding: ^2.1.1
  material_floating_search_bar_2: ^0.5.0
  geolocator: ^10.1.0
  dart_geohash: ^2.0.2
  geoflutterfire2: ^2.3.15
  flutter_dotenv: ^5.1.0
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.3.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.1.0
  http: ^1.2.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  auto_route_generator: ^7.2.0
  build_runner: ">=2.3.0 <4.0.0"

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/icon/
   - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  android: true
  image: "assets/icon/icon.png"
  ios: true
  android_12:
    color: "#FFFFFF"
    image: "assets/icon/icon.png"
    
