// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Q-0MKSzN0IpvklnNc1t4yPEpzQScC9o',
    appId: '1:928314563960:web:45b667f3b44f9953b3bc8d',
    messagingSenderId: '928314563960',
    projectId: 'heroes-cd74a',
    authDomain: 'heroes-cd74a.firebaseapp.com',
    storageBucket: 'heroes-cd74a.appspot.com',
    measurementId: 'G-H6Z8L0F1HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeZTR26o0EjvNza9B_kwjD41h6pF9yoF0',
    appId: '1:928314563960:android:3dc6523e4fb1163eb3bc8d',
    messagingSenderId: '928314563960',
    projectId: 'heroes-cd74a',
    storageBucket: 'heroes-cd74a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9CAK0XhZdzdXjpb9jo6R-XvT7IKSagSM',
    appId: '1:928314563960:ios:d1b69ea0890be865b3bc8d',
    messagingSenderId: '928314563960',
    projectId: 'heroes-cd74a',
    storageBucket: 'heroes-cd74a.appspot.com',
    iosBundleId: 'com.example.heroesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9CAK0XhZdzdXjpb9jo6R-XvT7IKSagSM',
    appId: '1:928314563960:ios:909db16a033f1ccfb3bc8d',
    messagingSenderId: '928314563960',
    projectId: 'heroes-cd74a',
    storageBucket: 'heroes-cd74a.appspot.com',
    iosBundleId: 'com.example.heroesApp.RunnerTests',
  );
}
